version: '3.8'


services:

  postgres_db:
    image: postgres:13.0-alpine
    ports:
      - '5433:5433'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./dev.env
    networks:
      - db-net

  django:
    build:
      context: ./django_unleashed
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py migrate && \
                    python manage.py collectstatic --no-input --clear && \
                    cp -r django_unleashed/static/admin static/ && \
                    rm -rf django_unleashed/static && \
                    gunicorn django_unleashed.wsgi --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/django_unleashed/static
      - media_volume:/home/app/django_unleashed/media
    expose:
      - 8000
    env_file:
      - ./dev.env
    environment:
      - POSTGRES_HOST=postgres_db
    depends_on:
      - postgres_db
    networks:
      - db-net
  
  nginx:
    build:
      context: ./nginX
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/home/app/django_unleashed/static
      - media_volume:/home/app/django_unleashed/media
    ports:
      - 80:80
    depends_on:
    - django
    networks:
      - db-net


volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  db-net:
    driver: bridge